import type { Metadata } from "next";
import "../globals.css";
import Footer from "@/components/Shared/Client/Footer";
import { AuthProvider } from "@/provider/ContextProvider";
import logo from '@/Assets/logo.png';
import Link from "next/link";
import Image from "next/image";


export const metadata: Metadata = {
    title: "PROTIPPZ",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={``}
            >
                <div className='p-4 bg-white shadow-md'>
                    <nav className="flex items-center justify-between container mx-auto">
                        <Link href={`/`}>
                            <Image src={logo} height={900} width={900} alt='logo' className='w-fit h-14' />
                        </Link>
                    </nav>
                </div>
                <AuthProvider>
                    <div className="min-h-[72vh] flex flex-col justify-center items-center">
                        {children}
                    </div>
                    <Footer />
                </AuthProvider>
            </body>
        </html>
    );
}
